# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run testAllaa
  displayName: 'npm testAllaa'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/jest-junit.xml'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/clover.xml'

# - task: PublishTestResults@2
#   enabled: false
#   displayName: Publish Test Results
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: '**/test_results/jest-junit.xml'
#     mergeTestResults: true

